### ISSUE TITLE
Multiple TTree keys when output ROOT file exceeds 30 MB

### ISSUE THREAD

**Issue by kyungeonchoi** [ponyisi/parquet_to_root#1]
### Story

Multiple TTree keys with the same tree name are generated when output ROOT file exceeds 30 MB.

### Assumptions

There seems like a limit during `TTree::Fill()` process.

### Acceptance Criteria

One key for the same tree name for ROOT file larger than 30 MB.

**Comment by ponyisi** [comment]
It's not actually a bug - ROOT periodically flushes the trees to file. When the tree is opened again only the latest key will be read.

However this is not really a necessary feature so I have disabled it with SetAutoSave(0).
