### ISSUE TITLE
Parquet to ROOT conversion speed

### ISSUE THREAD

**Issue by kyungeonchoi** [ponyisi/parquet_to_root#2]
### Story

A benchmark of parquet to ROOT TTree conversion:
- Single core of laptop
- 10 parquet input files (90 MB in total) - 80 branches
- Wall time: 3 min 18 s

### Acceptance Criteria

Any possibility to improve speed?

**Comment by ponyisi** [comment]
version 0.3.0 will speed up your particular use case (many scalars of primitive type). There should also be a mild speedup for arrays of primitive type although the exact amount is not yet known.
